.TH "oniguruma Directory Reference" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
oniguruma Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBenc\fP"
.br
.ti -1c
.RI "directory \fBsample\fP"
.br
.ti -1c
.RI "directory \fBwin32\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBregcomp\&.c\fP"
.br
.ti -1c
.RI "file \fBregenc\&.c\fP"
.br
.ti -1c
.RI "file \fBregerror\&.c\fP"
.br
.ti -1c
.RI "file \fBregexec\&.c\fP"
.br
.ti -1c
.RI "file \fBregext\&.c\fP"
.br
.ti -1c
.RI "file \fBreggnu\&.c\fP"
.br
.ti -1c
.RI "file \fBregparse\&.c\fP"
.br
.ti -1c
.RI "file \fBregposerr\&.c\fP"
.br
.ti -1c
.RI "file \fBregposix\&.c\fP"
.br
.ti -1c
.RI "file \fBregsyntax\&.c\fP"
.br
.ti -1c
.RI "file \fBregtrav\&.c\fP"
.br
.ti -1c
.RI "file \fBregversion\&.c\fP"
.br
.ti -1c
.RI "file \fBst\&.c\fP"
.br
.ti -1c
.RI "file \fBtestc\&.c\fP"
.br
.ti -1c
.RI "file \fBtestu\&.c\fP"
.br
.in -1c
