.TH "app_parent" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app_parent \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "evhtp_t * \fBevhtp\fP"
.br
.ti -1c
.RI "evbase_t * \fBevbase\fP"
.br
.ti -1c
.RI "char * \fBredis_host\fP"
.br
.ti -1c
.RI "uint16_t \fBredis_port\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file thread_design\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
