.TH "CodePointList2" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodePointList2 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "OnigCodePoint \fBcode\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8542 of file unicode\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
