.TH "Core evhtp functions" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core evhtp functions \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "EVHTP_EXPORT evhtp_t * \fBevhtp_new\fP (evbase_t *evbase, void *arg)"
.br
.ti -1c
.RI "EVHTP_EXPORT void \fBevhtp_free\fP (evhtp_t *evhtp)"
.br
.RI "\fIfree a evhtp_t context \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "EVHTP_EXPORT void evhtp_free (evhtp_t *evhtp)"

.PP
free a evhtp_t context 
.PP
\fBParameters:\fP
.RS 4
\fIevhtp\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "EVHTP_EXPORT evhtp_t* evhtp_new (evbase_t *evbase, void *arg)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
