.TH "evhtp_alias_t" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evhtp_alias_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evhtp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTAILQ_ENTRY\fP (\fBevhtp_alias_s\fP) next"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBalias\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 281 of file evhtp\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "evhtp_alias_t::TAILQ_ENTRY (\fBevhtp_alias_s\fP)"

.SH "Field Documentation"
.PP 
.SS "char* evhtp_alias_t::alias"

.PP
Definition at line 282 of file evhtp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
