.TH "Core evhtp functions" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core evhtp functions \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBevhtp_t\fP"
.br
.RI "\fImain structure containing all configuration information \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "EVHTP_EXPORT evhtp_t * \fBevhtp_new\fP (evbase_t *evbase, void *arg)"
.br
.RI "\fIcreates a new evhtp_t instance \fP"
.ti -1c
.RI "EVHTP_EXPORT void \fBevhtp_free\fP (evhtp_t *evhtp)"
.br
.RI "\fIfree a evhtp_t context \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "EVHTP_EXPORT void evhtp_free (evhtp_t *evhtp)"

.PP
free a evhtp_t context 
.PP
\fBParameters:\fP
.RS 4
\fIevhtp\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "EVHTP_EXPORT evhtp_t* evhtp_new (evbase_t *evbase, void *arg)"

.PP
creates a new evhtp_t instance 
.PP
\fBParameters:\fP
.RS 4
\fIevbase\fP the initialized event base 
.br
\fIarg\fP user-defined argument which is evhtp_t specific
.RE
.PP
\fBReturns:\fP
.RS 4
a new evhtp_t structure or NULL on error 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
