.TH "evhtp_defaults_5" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evhtp_defaults_5 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evhtp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBevhtp_callback_cb\fP \fBcb\fP"
.br
.ti -1c
.RI "\fBevhtp_pre_accept_cb\fP \fBpre_accept\fP"
.br
.ti -1c
.RI "\fBevhtp_post_accept_cb\fP \fBpost_accept\fP"
.br
.ti -1c
.RI "void * \fBcbarg\fP"
.br
.ti -1c
.RI "void * \fBpre_accept_cbarg\fP"
.br
.ti -1c
.RI "void * \fBpost_accept_cbarg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 270 of file evhtp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBevhtp_callback_cb\fP evhtp_defaults_5::cb"

.PP
Definition at line 271 of file evhtp\&.h\&.
.SS "void* evhtp_defaults_5::cbarg"

.PP
Definition at line 274 of file evhtp\&.h\&.
.SS "\fBevhtp_post_accept_cb\fP evhtp_defaults_5::post_accept"

.PP
Definition at line 273 of file evhtp\&.h\&.
.SS "void* evhtp_defaults_5::post_accept_cbarg"

.PP
Definition at line 276 of file evhtp\&.h\&.
.SS "\fBevhtp_pre_accept_cb\fP evhtp_defaults_5::pre_accept"

.PP
Definition at line 272 of file evhtp\&.h\&.
.SS "void* evhtp_defaults_5::pre_accept_cbarg"

.PP
Definition at line 275 of file evhtp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
