.TH "evthr" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evthr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBrdr\fP"
.br
.ti -1c
.RI "int \fBwdr\fP"
.br
.ti -1c
.RI "char \fBerr\fP"
.br
.ti -1c
.RI "ev_t * \fBevent\fP"
.br
.ti -1c
.RI "evbase_t * \fBevbase\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBlock\fP"
.br
.ti -1c
.RI "pthread_t * \fBthr\fP"
.br
.ti -1c
.RI "evthr_init_cb \fBinit_cb\fP"
.br
.ti -1c
.RI "void * \fBarg\fP"
.br
.ti -1c
.RI "void * \fBaux\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file evthr\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
