.TH "htparser" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
htparser \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "htpparse_error \fBerror\fP"
.br
.ti -1c
.RI "parser_state \fBstate\fP"
.br
.ti -1c
.RI "parser_flags \fBflags\fP"
.br
.ti -1c
.RI "eval_hdr_val \fBheval\fP"
.br
.ti -1c
.RI "htp_type \fBtype\fP"
.br
.ti -1c
.RI "htp_scheme \fBscheme\fP"
.br
.ti -1c
.RI "htp_method \fBmethod\fP"
.br
.ti -1c
.RI "unsigned char \fBmultipart\fP"
.br
.ti -1c
.RI "unsigned char \fBmajor\fP"
.br
.ti -1c
.RI "unsigned char \fBminor\fP"
.br
.ti -1c
.RI "uint64_t \fBcontent_len\fP"
.br
.ti -1c
.RI "uint64_t \fBorig_content_len\fP"
.br
.ti -1c
.RI "uint64_t \fBbytes_read\fP"
.br
.ti -1c
.RI "uint64_t \fBtotal_bytes_read\fP"
.br
.ti -1c
.RI "unsigned int \fBstatus\fP"
.br
.ti -1c
.RI "unsigned int \fBstatus_count\fP"
.br
.ti -1c
.RI "char * \fBscheme_offset\fP"
.br
.ti -1c
.RI "char * \fBhost_offset\fP"
.br
.ti -1c
.RI "char * \fBport_offset\fP"
.br
.ti -1c
.RI "char * \fBpath_offset\fP"
.br
.ti -1c
.RI "char * \fBargs_offset\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "unsigned int \fBbuf_idx\fP"
.br
.ti -1c
.RI "char \fBbuf\fP [PARSER_STACK_MAX]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file htparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
