.TH "htparse_hooks" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
htparse_hooks \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <htparse\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhtparse_hook\fP \fBon_msg_begin\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBmethod\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBscheme\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBhost\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBport\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBpath\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBargs\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBuri\fP"
.br
.ti -1c
.RI "\fBhtparse_hook\fP \fBon_hdrs_begin\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBhdr_key\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBhdr_val\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBhostname\fP"
.br
.ti -1c
.RI "\fBhtparse_hook\fP \fBon_hdrs_complete\fP"
.br
.ti -1c
.RI "\fBhtparse_hook\fP \fBon_new_chunk\fP"
.br
.ti -1c
.RI "\fBhtparse_hook\fP \fBon_chunk_complete\fP"
.br
.ti -1c
.RI "\fBhtparse_hook\fP \fBon_chunks_complete\fP"
.br
.ti -1c
.RI "\fBhtparse_data_hook\fP \fBbody\fP"
.br
.ti -1c
.RI "\fBhtparse_hook\fP \fBon_msg_complete\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file htparse\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBhtparse_data_hook\fP htparse_hooks::args"

.PP
Definition at line 82 of file htparse\&.h\&.
.SS "\fBhtparse_data_hook\fP htparse_hooks::body"

.PP
Definition at line 92 of file htparse\&.h\&.
.SS "\fBhtparse_data_hook\fP htparse_hooks::hdr_key"

.PP
Definition at line 85 of file htparse\&.h\&.
.SS "\fBhtparse_data_hook\fP htparse_hooks::hdr_val"

.PP
Definition at line 86 of file htparse\&.h\&.
.SS "\fBhtparse_data_hook\fP htparse_hooks::host"

.PP
Definition at line 79 of file htparse\&.h\&.
.SS "\fBhtparse_data_hook\fP htparse_hooks::hostname"

.PP
Definition at line 87 of file htparse\&.h\&.
.SS "\fBhtparse_data_hook\fP htparse_hooks::method"

.PP
Definition at line 77 of file htparse\&.h\&.
.SS "\fBhtparse_hook\fP htparse_hooks::on_chunk_complete"

.PP
Definition at line 90 of file htparse\&.h\&.
.SS "\fBhtparse_hook\fP htparse_hooks::on_chunks_complete"

.PP
Definition at line 91 of file htparse\&.h\&.
.SS "\fBhtparse_hook\fP htparse_hooks::on_hdrs_begin"

.PP
Definition at line 84 of file htparse\&.h\&.
.SS "\fBhtparse_hook\fP htparse_hooks::on_hdrs_complete"

.PP
Definition at line 88 of file htparse\&.h\&.
.SS "\fBhtparse_hook\fP htparse_hooks::on_msg_begin"

.PP
Definition at line 76 of file htparse\&.h\&.
.SS "\fBhtparse_hook\fP htparse_hooks::on_msg_complete"

.PP
Definition at line 93 of file htparse\&.h\&.
.SS "\fBhtparse_hook\fP htparse_hooks::on_new_chunk"

.PP
Definition at line 89 of file htparse\&.h\&.
.SS "\fBhtparse_data_hook\fP htparse_hooks::path"

.PP
Definition at line 81 of file htparse\&.h\&.
.SS "\fBhtparse_data_hook\fP htparse_hooks::port"

.PP
Definition at line 80 of file htparse\&.h\&.
.SS "\fBhtparse_data_hook\fP htparse_hooks::scheme"

.PP
Definition at line 78 of file htparse\&.h\&.
.SS "\fBhtparse_data_hook\fP htparse_hooks::uri"

.PP
Definition at line 83 of file htparse\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
