.TH "INamesArg" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
INamesArg \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBfunc\fP )(const UChar *, const UChar *, int, int *, regex_t *, void *)"
.br
.ti -1c
.RI "regex_t * \fBreg\fP"
.br
.ti -1c
.RI "void * \fBarg\fP"
.br
.ti -1c
.RI "int \fBret\fP"
.br
.ti -1c
.RI "OnigEncoding \fBenc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 491 of file regparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
