.TH "lambda_source_t" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lambda_source_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBfile\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.ti -1c
.RI "size_t \fBline\fP"
.br
.ti -1c
.RI "const char * \fBkeyword\fP"
.br
.ti -1c
.RI "size_t \fBkeylength\fP"
.br
.ti -1c
.RI "bool \fBshort_enabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file lambda-pp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
