.TH "lambda_t" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lambda_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBstart\fP"
.br
.ti -1c
.RI "\fBlambda_range_t\fP \fBdecl\fP"
.br
.ti -1c
.RI "\fBlambda_range_t\fP \fBbody\fP"
.br
.ti -1c
.RI "size_t \fBname_offset\fP"
.br
.ti -1c
.RI "size_t \fBdecl_line\fP"
.br
.ti -1c
.RI "size_t \fBbody_line\fP"
.br
.ti -1c
.RI "size_t \fBend_line\fP"
.br
.ti -1c
.RI "bool \fBis_short\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file lambda-pp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
