.TH "NodeOptInfo" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeOptInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMinMaxLen\fP \fBlen\fP"
.br
.ti -1c
.RI "\fBOptAncInfo\fP \fBanc\fP"
.br
.ti -1c
.RI "\fBOptExactInfo\fP \fBexb\fP"
.br
.ti -1c
.RI "\fBOptExactInfo\fP \fBexm\fP"
.br
.ti -1c
.RI "\fBOptExactInfo\fP \fBexpr\fP"
.br
.ti -1c
.RI "\fBOptMapInfo\fP \fBmap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3964 of file regcomp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
