.TH "OnigToken" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OnigToken \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum TokenSyms \fBtype\fP"
.br
.ti -1c
.RI "int \fBescaped\fP"
.br
.ti -1c
.RI "int \fBbase\fP"
.br
.ti -1c
.RI "UChar * \fBbackp\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   UChar * \fBs\fP"
.br
.ti -1c
.RI "   int \fBc\fP"
.br
.ti -1c
.RI "   OnigCodePoint \fBcode\fP"
.br
.ti -1c
.RI "   int \fBanchor\fP"
.br
.ti -1c
.RI "   int \fBsubtype\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBlower\fP"
.br
.ti -1c
.RI "      int \fBupper\fP"
.br
.ti -1c
.RI "      int \fBgreedy\fP"
.br
.ti -1c
.RI "      int \fBpossessive\fP"
.br
.ti -1c
.RI "   } \fBrepeat\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBnum\fP"
.br
.ti -1c
.RI "      int \fBref1\fP"
.br
.ti -1c
.RI "      int * \fBrefs\fP"
.br
.ti -1c
.RI "      int \fBby_name\fP"
.br
.ti -1c
.RI "      int \fBexist_level\fP"
.br
.ti -1c
.RI "      int \fBlevel\fP"
.br
.ti -1c
.RI "   } \fBbackref\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      UChar * \fBname\fP"
.br
.ti -1c
.RI "      UChar * \fBname_end\fP"
.br
.ti -1c
.RI "      int \fBgnum\fP"
.br
.ti -1c
.RI "   } \fBcall\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBctype\fP"
.br
.ti -1c
.RI "      int \fBnot\fP"
.br
.ti -1c
.RI "   } \fBprop\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2269 of file regparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
