.TH "OptMapInfo" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptMapInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMinMaxLen\fP \fBmmd\fP"
.br
.ti -1c
.RI "\fBOptAncInfo\fP \fBanc\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "UChar \fBmap\fP [ONIG_CHAR_TABLE_SIZE]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3956 of file regcomp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
