.TH "type_cclass_key" 3 "Thu May 21 2015" "Version 1.2.10-dev" "Libevhtp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_cclass_key \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "OnigEncoding \fBenc\fP"
.br
.ti -1c
.RI "int \fBnot\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4851 of file regparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libevhtp from the source code\&.
